### ISSUE TITLE
Example does not build

### ISSUE THREAD

**Issue by jmount1992** [BlueBrain/Pydoxine#13]
Hi,

I would really like to use this software however I cannot even get the example build and would like some direction please.

First I fixed some minor issues in some of the various CMake files:

In the Pydoxine/example/CMakeLists.txt
1. I had to comment out the include(GitExternal) and include(Common). This might be because there is nothing in the Pydoxine/example/CMake folder.
2. As I could not include common I was required to change common_find_package to find_package as well as comment out common_find_package_post()

In Pydoxine/example/python/CMakeLists.txt
1. In the docstrings function call I had to change it to docstrings(WRAPPING_SOURCES, WRAPPED_HEADERS, ${CMAKE_SOURCE_DIR}). As the docstrings function took in 3 arguments even though the 3rd argument is not used. 
3. I had to comment the configure_file() call at the bottom of the cmake file as it throws an error. I assume the error is because trying to read and write to the same file __init__.py. However, as there are no configurable variables in __init__.py I assumed this line was not required. 

Fixing those allows me to run cmake on the Pydoxine/example/CMakeLists.txt file without any cmake errors. However then I ran into build errors.

When running the command to build the init_docstrings.cpp file I get several warnings that look like this: 
```
/home/james/Desktop/Pydoxine/example/build/docstrings/cpp/index.rst:1: WARNING: Error in "doxygenfunction" directive:
unknown option: "no-header".

.. doxygenfunction:: example::module::Example::publicMethod()
   :no-header:
   :project: PydoxineExample
```

I also then get a build warning while compiling example.cpp.o that says the getDoxygenComment function is used within the docstrings.h file but never defined. I know this is just a warning and that the getDoxygenComment function is defined within docstrings.cpp. However, is this warning usual?

Finally, I get a error after linking the shared library stating "/usr/bin/ld: cannot open output file /example/_example.so: No such file or directory". This results in no example.so file being created.

Please any help would be appreciated.

Cheers,
James

**Comment by hernando** [comment]
Hi James,
The example is not building because you have to clone the git submodule with the CMake scripts it uses. You can either add --recursive to the git clone command when cloning this repository or once it's cloned do git submodule update --init. That's not clear from the documentation I'll try to update it. Another documentation error is that the latest Sphinx version is not supported. I don't know which is the most up to date supported version, but I can tell you that 1.3.6 works.
Try again like this and let me know which problems you encounter.

**Comment by hernando** [comment]
In fact there were some errors, I've created #14 to fix them. The parameter which isn't apparently used, is used by a configure_file. If you happen to be using Mac and the latest boost version from brew, there's another problem in the CMake/common submodule. You can apply the patch by hand if needed (Eyescale/Cmake#587)

**Comment by jmount1992** [comment]
Thanks for the information and taking a look! Sorry I'm a new user to
Github and software isn't my strong point so I'm not too familiar with
things.

Cheers,
James

**Comment by jmount1992** [comment]
@hernando thanks for all your help so far. I cloned your fixes branch and ran the command "git submodule update --init" and worked a charm. However, running cmake on the example still resulted in an error stating "could not find Python Libs". However, I knew I had this library installed as I used it in a different project. I found that changing the following line of code the in Pydoxine/example/CMakeLists.txt file from:
`common_find_package(PythonLibs REQUIRED)`
to:
`common_find_package(PythonLibs 2.7 REQUIRED)`
Solved the cmake error. I'm running on Ubuntu 16.04, if that could explain why.

The example then compiled successfully, however it did still spit out the following error:
```
Pydoxine/example/build/docstrings/cpp/index.rst:31: ERROR: Error in "doxygenvariable" directive:
unknown option: "no-header".

.. doxygenvariable:: example::BaseExample::theThing
   :no-link:
   :no-header:
   :project: PydoxineExample
```
Then when I tried to import the example.so file into Python I got the following error:
`ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0: undefined symbol: PyUnicode_AsUTF8String`

I thought this might because I was using Sphinx 1.6.5. So I installed Sphinx 1.3.6 instead. The same build and runtime errors occurred. I googled the error and thought it maybe to do with Python 2 and 3 conflicting and so I also added 2.7 when finding the PythonInterp package. Still no luck.

I have created boost python modules before so I'm not sure what the problem is.

If anyone can point me in the right direction would be greatly appreciated.

**Comment by jmount1992** [comment]
Also if sphinx 1.3.6 is required why not make in the PythonDocstrings.cmake force it using the EXACT keyword?

**Comment by hernando** [comment]
The CMake scripts prefer Python 3 over 2. The two versions cannot be mixed at all. Most probably you have the Boost.Python library for Python 3, but you are missing the headers for the Python 3 library.
If you're using Ubuntu 16.04 everything should be relatively simple if you use the default packages from the repositories. The list of all packages I'm aware is: doxygen, python3-dev, libboost-python-dev and python3-sphinx (if you have installed this one through pip or have another version for python2 installed it may cause problems). After you're sure you have all the dependencies in place, remove the CMakeCache.txt file in the build directory and start over because some of the cached variables must be pointing to Python2 and they are not changed by running cmake again.

**Comment by hernando** [comment]
Requiring Sphinx 1.3 is a good point.

**Comment by hernando** [comment]
Version 1.3 is already requested, the REQUIRED word is not used because we don't want to make Pydoxine a hard dependency of the projects using it, so they can be built even when Pydoxine's dependencies are not met.

**Comment by jmount1992** [comment]
My CMake knowledge isn't great. But if you use the EXACT keyword when calling find_package does that create a hard dependency? I completely understand not using the REQUIRED keyword though, simply wondering if the EXACT implicitly means REQUIRED.

**Comment by hernando** [comment]
Hard dependency isn't probably the best word to refer to what you mean, but I get your point. I didn't know about EXACT and it's true that with REQUIRED other versions may be accepted, but only if they match the minor version number.

**Comment by hernando** [comment]
I've added EXACT to find_package for Sphinx. I assume it works for you now so I'm closing this ticket.
